vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        missions:
            uri_prefix: /upload/images/articles
            upload_destination: '%kernel.project_dir%/public/upload/images/articles'
