controller_security:
    resource: ../src/Controller/SecurityController.php
    type: attribute

controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix: client_

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix: admin_
    prefix: /admin/

controllers_employee:
    resource: ../src/Controller/Employee
    type: attribute
    name_prefix: employee_
    prefix: /employee/

app_pdf_generate_orders:
    path: /pdf/generate/orders
    controller: App\Controller\Back\PdfGenerateController::generateOrdersPdf

app_pdf_generate_employees:
    path: /pdf/generate/employees
    controller: App\Controller\Back\PdfGenerateController::generateEmployeesPdf

